#pragma once

#include "Book.h"

extern Book const	b1("Bible", "Jesus", "Classical"),
			b2 = b1,		//Copy constructor
			b3 = b1,
			b4("Illiad", "Homer", "Classical"),
			b5 = b4,
			b6 = b4,
			b7("Odyssey", "Homer", "Classical"),
			b8("The Madhyama Vyayoga", "Bhasa", "Classical"),
			b9("Pratima-nataka", "Bhasa", "Classical"),
			b10("Chu Ci", "Qu Yuan", "Classical"),
			b11("Lament for Ying", "Qu Yuan", "Classical"),
			b12("Heroides", "Ovid", "Classical"),
			b13("Metamorphoses", "Ovid", "Classical"),
			b14("Yoga Vasistha", "Valmiki", "Classical"),
			b15("The Ramayana", "Valmiki", "Classical"),
			b16("The Canterbury Tales", "Geoffrey Chaucer", "Medieval"),
			b17("Troilus and Criseyde", "Geoffrey Chaucer", "Medieval"),
			b18("Drinking Alone by Moonlight", "Li Bai", "Medieval"),
			b19("In the Mountains on a Summer Day", "Li Bai", "Medieval"),
			b20("The Diary of Lady Murasaki", "Murasaki Shikibu", "Medieval"),
			b21("The Tale of Genji", "Murasaki Shikibu", "Medieval"),
			b22("Divani Shamsi Tabriz", "Rumi", "Medieval"),
			b23("Masnavi", "Rumi", "Medieval"),
			b24("Don Quixote", "Miguel de Servantes", "Renaissance"),
			b25("Novelas Ejemplares", "Miguel de Servantes", "Renaissance"),
			b26("Romeo and Juliet", "William Shakespeare", "Renaissance"),
			b27("Hamlet", "William Shakespeare", "Renaissance"),
			b28("Discourses on Livy", "Niccolo Machiavelli", "Renaissance"),
			b29("The Prince", "Niccolo Machiavelli", "Renaissance"),
			b30("The Blazing World", "Margaret Cavendish", "Renaissance"),
			b31("Observations upon Experimental Philosophy", "Margaret Cavendish", "Renaissance"),
			b32("Fair Goldilocks", "Marie-Catherine d'Aulnoy", "Renaissance"),
			b33("The Dolphin", "Marie-Catherine d'Aulnoy", "Renaissance"),
			b35("Sense and Sensibility", "Jane Austen", "Industrial"),
			b34("Pride and Prejudice", "Jane Austen", "Industrial"),
			b36("The Tell-Tale Heart", "Edgar Allen Poe", "Industrial"),
			b37("The Raven", "Edgar Allen Poe", "Industrial"),
			b38("Boris Godunov", "Alexander Pushkin", "Industrial"),
			b39("Eugene Onegin", "Alexander Pushkin", "Industrial"),
			b40("Faust", "Johann Wolfgang", "Industrial"),
			b41("The Sorrows of Young Werther", "Johann Wolfgang", "Industrial"),
			b42("Frankenstein", "Mary Shelley", "Industrial"),
			b43("The Last Man", "Mary Shelley", "Industrial"),
			b44("Ulysses", "James Joyce", "Modern"),
			b45("Dubliners", "James Joyce", "Modern"),
			b46("A Bird Came Down the Walk", "Emily Dickison", "Modern"),
			b47("Success is Counted Sweetest", "Emily Dickison", "Modern"),
			b48("War and Peace", "Leo Tolstoy", "Modern"),
			b49("Anna Karenina", "Leo Tolstoy", "Modern"),
			b50("The Adventures of Huckleberry Finn", "Mark Twain", "Modern"),
			b51("The Adventures of Tom Sawyer", "Mark Twain", "Modern"),
			b52("The Tale of Peter Rabbit", "Beatrix Potter", "Modern"),
			b53("The Tailor of Gloucester", "Beatrix Potter", "Modern"),
			b54("The Beautiful and the Damned", "F. Scott Fitzgerald", "Modern"),
			b55("This Side of Paradise", "F. Scott Fitzgerald", "Modern"),
			b56("The Home and the World", "Rabindranath Tagore", "Atomic"),
			b57("The Gardener", "Rabindranath Tagore", "Atomic"),
			b58("The War of the Worlds", "H. G. Welss", "Atomic"),
			b59("The Time Machine", "H. G. Welss", "Atomic"),
			b60("Rossum's Universal Robots (R.U.R)", "Karel Capok", "Information"),
			b61("War with the Newts", "Karel Capok", "Information"),
			b62("Lecturas para mujeres", "Gabriela Mistral", "Information"),
			b63("Sonetos de la Muerte", "Gabriela Mistral", "Information");